* TODO User interface [0/4]
- [ ] Setting for amount of time the beam is down before a message is sent
- [ ] Setting for how much the intesity has to increase/decrease before a message is sent
- [ ] Setting for how much the dose rate per hour has to change before a message is sent

* TODO Message Contents [0/6]
- [ ] How long has the beam been down
- [ ] Mean of the BPM
- [ ] Mean of the MWPC
- [ ] FWHM of the BPM
- [ ] FWHM of the MWPC
- [ ] Intensity of beam, from SEC 1

* TODO Data retrival [4/7]
- [X] Write code to download BPM data from https://ps-irrad.web.cern.ch/irrad/bpm.php
- [X] Write regex to extract data from the html downloaded in the point above.
- [X] Write a class for getting data from MWPC, can be based on adams code.
- [X] Write a class for getting data from the SEC.
- [ ] Implement the method for finding the fwhm of the MWPC that adam used, and compare it to the one currentyl in use
- [ ] Fix the checking of the BPM using 3 indexes, also currently only checking the x-axis
- [ ] Fix the check for SEC 1 as is currently saying there is no beam even when there is

* TODO Database for strong references and settings [3/4]
- [X] Setup SQLITE3 database
- [X] Write functions for opening and closing the database
- [X] Write functions for inserting data to tables
- [ ] Write functions for changing values of settings and references

* TODO Other [1/1]
- [X] Ask Maurice Glaser how to obtain data from th BPM.
  Email sent, waiting for reply. 2015-07-03 Fri 10:23.
  Wrote function for extracting the data from https://ps-irrad.web.cern.ch/irrad/bpm.php, making this unnesseary.

* Notes
- Intensity can be gathered from SEC 1
- The BPM and MWPC show beam profile with mean and FWHM
- SEC 2 is affected too much by objects in the beamline and is therefore not used
- Check data every 10 minutes.
- In order to know how long the beam has been down, store the time that downtime was
  detected
