* TODO User interface [3/3]
- [X] Setting for amount of time the beam is down before a message is sent
- [X] Setting for how much the intesity has to increase/decrease before a message is sent
- [X] Setting for how much the dose rate per hour has to change before a message is sent
- [ ] Update text view with last two messages
- [ ] Connect the GUI to the rest of the program

* TODO Message Contents [6/8]
- [ ] How long has the beam been down
- [X] Mean intensity of the BPM 
- [X] Mean intensity of the MWPC
- [X] FWHM of the BPM
- [X] FWHM of the MWPC
- [X] Intensity of beam, from SEC 1
- [X] Check centering of the beam for BPM and MWPC
- [ ] Should be checking beam intensity first, but it doesn't

* TODO Data retrival [8/8]
- [X] Write code to download BPM data from https://ps-irrad.web.cern.ch/irrad/bpm.php
- [X] Write regex to extract data from the html downloaded in the point above.
- [X] Write a class for getting data from MWPC, can be based on adams code.
- [X] Write a class for getting data from the SEC.
- [X] Implement the method for finding the fwhm of the MWPC that adam used, and compare it to the one currentyl in use
- [X] Fix the checking of the BPM using 3 indexes, also currently only checking the x-axis
- [X] Fix the check for SEC 1 as is currently saying there is no beam even when there is
- [X] Fix that the MWPC class crashes when there is no beam.

* TODO Messaging [1/2]
- [X] Find a way to avoid sending an error message several times for discrepancies in the same varible.
  As an example if the FHWM of BPM4 decreases to under 70% of the reference, send an email, but don't
  send a new email about it before after it has gone back to normal.
- [ ] Use a third number for the last column in the messages, to allow sending a beam down email after
  a beam off centre email has been sent.

* TODO Database for strong references and settings [5/6]
- [X] Setup SQLITE3 database
- [X] Write functions for opening and closing the database
- [X] Write functions for inserting data to tables
- [ ] Write functions for changing values of settings and references
- [X] Create a table for storing user info.
- [X] Implement the __del__(self) function so that the database connection is closed when the python destructor is called on the object.

* TODO Other [1/1]
- [X] Ask Maurice Glaser how to obtain data from th BPM.
  Email sent, waiting for reply. 2015-07-03 Fri 10:23.
  Wrote function for extracting the data from https://ps-irrad.web.cern.ch/irrad/bpm.php, making this unnesseary.

* Notes
- Intensity can be gathered from SEC 1
- The BPM and MWPC show beam profile with mean and FWHM
- SEC 2 is affected too much by objects in the beamline and is therefore not used
- Check data every 10 minutes.
- In order to know how long the beam has been down, store the time that downtime was
  detected
